// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class CarteDebit extends CarteBancaire {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat periodeDebit;

	/**
	 * 
	 * @param montant 
	 * @return 
	 */
	public EcorePrimitiveTypes.EFloat retirer(EcorePrimitiveTypes.EFloat montant) {
	}

	/**
	 * 
	 * @return 
	 */
	protected boolean ValiderRetrait() {
	}
};
