// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public abstract class CarteBancaire {
	/**
	 * 
	 */
	public Reseau reseau;

	/**
	 * 
	 * @param montant 
	 * @return 
	 */
	protected EcorePrimitiveTypes.EFloat retirer(EcorePrimitiveTypes.EFloat montant) {
	}

	/**
	 * 
	 * @return 
	 */
	protected boolean ValiderRetrait() {
	}
};
