// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class CarteFactory {
	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public CarteBancaire getCarte(String type) {
	}
};
