// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class CarteCredit extends CarteBancaire {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat Plafond;
};
