// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class ClientMoralFactory extends ClientFactory {
	/**
	 * 
	 * @return 
	 */
	protected Client createClient() {
	}
};
