// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public abstract class ClientFactory {
	/**
	 * 
	 * @return 
	 */
	protected Client createClient() {
	}

	/**
	 * 
	 * @return 
	 */
	public Client getClient() {
	}
};
