// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class clientPhysique extends Client {
	/**
	 * 
	 */
	protected EcorePrimitiveTypes.EDate dateNaissance;
	/**
	 * 
	 */
	public Etat etat;
	/**
	 * 
	 */
	public Client client;

	/**
	 * 
	 * @param compte 
	 */
	public void ajoutCompte(CompteBanquaire compte) {
	}
};
