// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class ClientMoral extends Client {
	/**
	 * 
	 */
	private String numSiret;
	/**
	 * 
	 */
	public clientPhysique[] clientphysique;

	/**
	 * 
	 * @param compte 
	 */
	public void ajoutCompte(CompteBanquaire compte) {
	}
};
