// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class CompteBanquaire {
	/**
	 * 
	 */
	protected String numCompte;
	/**
	 * 
	 */
	protected EcorePrimitiveTypes.EFloat solde;
	/**
	 * 
	 */
	protected EcorePrimitiveTypes.EFloat montantDecouver;
	/**
	 * 
	 */
	public CarteBancaire cartebancaire;
	/**
	 * 
	 */
	public Memento memento;

	/**
	 * 
	 * @param montant 
	 */
	public void ajoutArgent(EcorePrimitiveTypes.EFloat montant) {
	}

	/**
	 * 
	 * @param montant 
	 * @param montantRetiré 
	 */
	public void retrait(EcorePrimitiveTypes.EFloat montant, EcorePrimitiveTypes.EFloat montantRetiré) {
	}

	/**
	 * 
	 * @return 
	 */
	public EcorePrimitiveTypes.EFloat consulterSolde() {
	}

	/**
	 * 
	 */
	public void saveState() {
	}

	/**
	 * 
	 * @return 
	 */
	public Memento getState() {
	}
};
