// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public abstract class CompteBuilder {
	/**
	 * 
	 */
	public void BuildCompte()() {
	}
};
