// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class ConcreteCompteBuilder extends CompteBuilder {
	/**
	 * 
	 */
	public void BuildCompte() {
	}

	/**
	 * 
	 * @return 
	 */
	public CompteBanquaire getCompte() {
	}
};
