// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class entre10Et18Ans extends Etat {
	/**
	 * 
	 */
	public void retirer() {
	}
};
