// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class Memento {
	/**
	 * 
	 */
	protected EcorePrimitiveTypes.EFloat solde;
	/**
	 * 
	 */
	public diag_class.Memento memento;
};
