// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class Paiement {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat montant;
	/**
	 * 
	 */
	private String pays;
};
