// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaRoyaumeUnis extends RemboursementVisa {
};
