// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public abstract class Reseau {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat coutReseau;

	/**
	 * 
	 * @return 
	 */
	public EcorePrimitiveTypes.EFloat Remboursement() {
	}

	/**
	 * 
	 */
	public void effectuerTransaction() {
	}
};
