// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package diag_class;

/************************************************************/
/**
 * 
 */
public class Visa extends Reseau {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EFloat coutReseau = 0.5;

	/**
	 * 
	 */
	public void effectuerTransaction() {
	}

	/**
	 * 
	 * @param paiement 
	 */
	public void remboursement(Paiement paiement) {
	}
};
