// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class CarteFactory {
	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public CarteBancaire creerCarte(String type, Reseau r, CompteBancaire compte, Client c) {
		if(type == "credit") {
			Float plafond = (float) 3000;
			return new CarteBancaireCredit(r, c, compte, plafond);
		} else if(type == "debit") {
			Float delais = (float) 3000;
			return new CarteBancaireDebit(r, c, compte, delais);
		} else {
			return null;
		}
	}
};
