// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaEtatsUnis extends RemboursementVisa {
	public RemboursementVisaEtatsUnis() {
		retenue = (float) 0.2;
	}
};
