// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaResteMonde extends RemboursementVisa {
	public RemboursementVisaResteMonde() {
		retenue = (float) 0.3;
	}
};
