// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaFrance extends RemboursementVisa {

	public RemboursementVisaFrance() {
		retenue = (float) 0.05;
	}
};
