// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaRoyaumeUnis extends RemboursementVisa {
	public RemboursementVisaRoyaumeUnis() {
		retenue = (float) 0.25;
	}
};
