// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaPortugal extends RemboursementVisa {
	public RemboursementVisaPortugal() {
		retenue = (float) 0.15;
	}
};
