// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class RemboursementVisaEspagne extends RemboursementVisa {
	
	public RemboursementVisaEspagne() {
		retenue = (float) 0.1;
	}
};
