// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class ReseauFactory {
	
	public Reseau crerReseau(String r) {
		if(r == "Visa") {
			return new ReseauVisa();
		} else if(r == "MasterCard") {
			return new ReseauMasterCard();
		} else {
			return null;
		}
	}
	
};
